### PR TITLE
Always use check_call when running a terraform command

### PR DESCRIPTION
**Pull request by dnouri**
Forgive the scrappy PR, but I was surprised to see that the default here is to suppress stderr output in case executing a terraform command fails. So I would only get the message "returned nonzero exit code" or some such, rather than being able to read what actually went wrong, i.e. the stderr output. Is there any case where you would *not* want this output? I'd argue that for a testing tool, the reasonable default is to be verbose in case of error.

### CODE REVIEW

**Comment by kapilt** [comment]
the issue is at scale it doesn't work as a default, its quite noisy, using -s -v will log output. i agree we want to do a better capture and return of output by default IFF there is an error. However simply switching to check_call by default isn't appropriate

**Comment by dnouri** [comment]
We're talking about test errors here though, right? Not failures. If my test errors, I will be happy if my test tool tells me what went wrong without the use of a debug flag.

**Comment by dnouri** [comment]
Or maybe I'm missing a use case here where we are expecting the terraform commands to fail, and we're testing against that?

**Comment by kapilt** [comment]
we want the full output only on error, not on success. if you have a high cardinality of tests then the rest becomes line noise. switching to check_call means its not differentiated on success vs failure.

**Comment by kapilt** [comment]
the default for pytest is squelching stdout/stderr, so there really isn't much line noise to deal with here, its probably simplest to merge as is, the alternative is capture stdout/stderr in the exception and then print/log on err catch before re-raise.

**Pull request merged**
